### PR TITLE
chore: remove package lock

### PR DESCRIPTION
**Pull request by nickmccurdy**

### CODE REVIEW

**Comment by benmonro** [comment]
@nickmccurdy  want to be admin on this repo?  😀

**Comment by nickmccurdy** [comment]
You mean in general? I don't think I need admin access to this, seems like the issue is with the ESLint config and updated packages. I'll see if I can figure it out.

**Comment by benmonro** [comment]
No I mean like wet aren't using night watch anymore so I'm looking for someone who wants it lol

**Comment by nickmccurdy** [comment]
I'm not very familiar with it honestly. I'm just updating it for maintenance purposes and to get the npm usage consistent with the rest of the organization to make it easier to contribute to.

**Comment by nickmccurdy** [comment]
The tests are still failing as they are on master. I've opened #156 so we can troubleshoot the issue in isolation. Once that's merged I will continue updating this.

**Comment by benmonro** [comment]
Ok well it's all yours regardless feel free to merge whatever you like

**Pull request merged**
